# Change these first
owner: tauronik # Your GitHub organization or username, where this repository lives
repo: tauro-upptime # The name of this repository

sites:
  - name: Tauronik IT Website
    url: https://www.tauronik.de
  - name: Firmentabata
    url: https://firmentabata.de
  - name: Tauronik IT Support
    url: https://support.tauromax.de
  - name: Tauronik IT Wiki
    url: https://wiki.tauronik.de
  - name: Tauronik IT Webmail  
    url: https://webmail.tauronik.de
  - name: Tanzschule Teltow
    url: https://www.tanzschule-teltow.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /tauro-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tauronik Upptime
  introTitle: "Tauronik IT Systemhaus **Webservice Status Page**"
  introMessage: **Real-time** website status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Impressum
      href: https://www.tauronik.de/impressum/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
