# Change these first
owner: tauronik # Your GitHub organization or username, where this repository lives
repo: tauro-upptime # The name of this repository

sites:
  - name: www.tauronik.de
    url: https://www.tauronik.de
  - name: firmentabata.de
    url: https://firmentabata.de
  - name: support.tauromax.de
    url: https://support.tauromax.de
  - name: wiki.tauronik.de
    url: https://wiki.tauronik.de
  - name: webmail.tauronik.de  
    url: https://webmail.tauronik.de
  - name: Server JULIET
    url: https://juliet.tauronik.de:5001
    __dangerous__insecure: true
  - name: Server CHARLY
    url: https://charlie.tauronik.de:5001
  - name: Server BRAVO
    url: https://bravo.tauronik.de:10000
  - name: Server TNK-VH-02
    url: https://tnk-vh-02.tauronik.de:8006
    __dangerous__insecure: true         
  - name: www.tanzschule-teltow.de
    url: https://www.tanzschule-teltow.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /tauro-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Tauronik Upptime
  theme: night
  introTitle: "Tauronik IT Systemhaus **Webservice Status Page**"
  introMessage: "**Real-time** website status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Impressum
      href: https://www.tauronik.de/impressum.html
  links:
    - rel: stylesheet
      href: https://cdn.statically.io/gh/tauronik/tauro-upptime/master/assets/custom.css     

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
